CREATE TABLE [dbo].[Business](
	[Id] [int] NOT NULL IDENTITY,
	[MerchantId] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Business]  WITH CHECK ADD  CONSTRAINT [FK_Business_Merchant] FOREIGN KEY([MerchantId])
REFERENCES [dbo].[Merchant] ([Id])
GO

ALTER TABLE [dbo].[Business] CHECK CONSTRAINT [FK_Business_Merchant]
GO


